name: Bug reports for commands
about: For bugs that involve commands found within Red.
title: ''
labels: 'Type: Bug'
assignees: ''
issue_body: true
inputs:
- type: description
  attributes:
    value: |
      Thank you for taking the time to fill out an issue. This template is meant for any issues related to commands.
      If you require help with installing Red we ask that you join our [Discord server](https://discord.gg/red)
- type: input
  attributes:
    label: "What Red version are you using?"
    placeholder: 3.4.5
    required: true
- type: dropdown
  attributes:
    label: "Cog name"
    description: "From which cog does the command come from?"
    required: true
    choices:
      - Admin
      - Alias
      - Audio
      - Bank
      - Cleanup
      - CogManagerUI
      - Core
      - Customcom
      - Dev
      - Downloader
      - Economy
      - Filter
      - General
      - Image
      - Mod
      - Modlog
      - Mutes
      - Permissions
      - Reports
      - Streams
      - Trivia
      - Warnings
- type: input
  attributes:
    label: "Command name"
    description: "What is the command that caused the error?"
    placeholder: "play"
    required: true
- type: textarea
  attributes:
    label: "What did you expect to happen?"
    required: true
- type: textarea
  attributes:
    label: "What actually happened?"
    description: |
      A clear and concise description of what the bug is.
      If the issue is visual in nature, consider posting a screenshot.
    required: true
- type: textarea
  attributes:
    label: "How can we reproduce this error?"
    description: "List of steps required to reproduce this error."
    value: |
      1.
      2.
      3.
      ...
    required: true
