name: Bug report
about: "For bugs that don't involve a command."
title: ''
labels: 'Type: Bug'
assignees: ''
issue_body: true
inputs:
- type: description
  attributes:
    value: |
      Thank you for taking the time to fill out an issue. This template is meant for any issues not related to any existing command.
      If you require help with installing Red we ask that you join our [Discord server](https://discord.gg/red)
- type: input
  attributes:
    label: "What Red version are you using?"
    placeholder: 3.4.5
    required: true
- type: textarea
  attributes:
    label: "What were you trying to do?"
    required: true
- type: textarea
  attributes:
    label: "What did you expect to happen?"
    required: true
- type: textarea
  attributes:
    label: "What actually happened?"
    description:  |
      If the issue is visual in nature, consider posting a screenshot.
    required: true
- type: textarea
  attributes:
    label: "How can we reproduce this error?"
    description: |
      List of steps required to reproduce the error. If the bug is code related, a minimal code example that reproduces the problem would be a big help.
    value: |
      1.
      2.
      3.
      ...
    required: true
